allowBuilds:
  '@swc/core': true
  rs-module-lexer: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@swc/core-darwin-arm64@1.15.41'
  - '@swc/core-darwin-x64@1.15.41'
  - '@swc/core-linux-arm-gnueabihf@1.15.41'
  - '@swc/core-linux-arm64-gnu@1.15.41'
  - '@swc/core-linux-arm64-musl@1.15.41'
  - '@swc/core-linux-ppc64-gnu@1.15.41'
  - '@swc/core-linux-s390x-gnu@1.15.41'
  - '@swc/core-linux-x64-gnu@1.15.41'
  - '@swc/core-linux-x64-musl@1.15.41'
  - '@swc/core-win32-arm64-msvc@1.15.41'
  - '@swc/core-win32-ia32-msvc@1.15.41'
  - '@swc/core-win32-x64-msvc@1.15.41'
  - '@swc/core@1.15.41'
  - prettier@3.8.4
  - '@aarsteinmedia/lottie-web@1.4.0'
