import { type AnimationData, type AnimationDirection, type AnimationItem, type AnimationSettings, type LottieManifest, type Vector2 } from '@aarsteinmedia/lottie-web';
import renderPlayer from '../templates/player';
import renderControls from '../templates/controls';
import { PlayMode, PlayerState, PreserveAspectRatio, RendererType } from '../enums';
import { AnimationAttributes, AnimateOnScroll, Autoplay, Controls, Loop, Subframe } from '../types';
import PropertyCallbackElement from '../elements/helpers/PropertyCallbackElement';
export default class DotLottiePlayer extends PropertyCallbackElement {
    constructor();
    connectedCallback(): Promise<void>;
    disconnectedCallback(): void;
    shadow: ShadowRoot;
    template: HTMLTemplateElement;
    protected _renderControls: typeof renderControls;
    protected _render: typeof renderPlayer;
    static get observedAttributes(): string[];
    attributeChangedCallback(name: string, _oldValue: unknown, value: string): Promise<void>;
    static get observedProperties(): string[];
    propertyChangedCallback(name: string, _oldValue: unknown, value: unknown): void;
    set animateOnScroll(value: AnimateOnScroll);
    get animateOnScroll(): AnimateOnScroll;
    set autoplay(value: Autoplay);
    get autoplay(): Autoplay;
    set background(value: string);
    get background(): string;
    set controls(value: Controls);
    get controls(): Controls;
    set count(value: number);
    get count(): number;
    set description(value: string | null);
    get description(): string | null;
    set direction(value: AnimationDirection);
    get direction(): AnimationDirection;
    set hover(value: boolean);
    get hover(): boolean;
    set intermission(value: number);
    get intermission(): number;
    set loop(value: Loop);
    get loop(): Loop;
    set mode(value: PlayMode);
    get mode(): PlayMode;
    set objectfit(value: string);
    get objectfit(): string;
    set preserveAspectRatio(value: PreserveAspectRatio | null);
    get preserveAspectRatio(): PreserveAspectRatio | null;
    set renderer(value: RendererType);
    get renderer(): RendererType;
    set simple(value: boolean);
    get simple(): boolean;
    set speed(value: number);
    get speed(): number;
    set src(value: string | null);
    get src(): string | null;
    set subframe(value: Subframe);
    get subframe(): Subframe;
    private _multiAnimationSettings;
    getMultiAnimationSettings(): AnimationSettings[];
    setMultiAnimationSettings(settings: AnimationSettings[]): void;
    private _segment?;
    setSegment(segment: Vector2): void;
    getSegment(): Vector2 | undefined;
    protected _container: HTMLElement | null;
    playerState: PlayerState;
    protected _isSettingsOpen: boolean;
    protected _seeker: number;
    private _currentAnimation;
    private _animations;
    private _intersectionObserver?;
    private _lottieInstance;
    protected _identifier: string;
    protected _errorMessage: string;
    private _isBounce;
    private _isDotLottie;
    private _manifest?;
    protected _playerState: {
        prev: PlayerState;
        count: number;
        loaded: boolean;
        visible: boolean;
        scrollY: number;
        scrollTimeout: NodeJS.Timeout | null;
    };
    private _getOptions;
    private _addIntersectionObserver;
    load(src: string | null): Promise<void>;
    getManifest(): LottieManifest | undefined;
    private _toggleEventListeners;
    private _addEventListeners;
    private _removeEventListeners;
    private _loopComplete;
    private _enterFrame;
    private _complete;
    private _DOMLoaded;
    private _dataReady;
    private _dataFailed;
    private _handleWindowBlur;
    private _mouseEnter;
    private _mouseLeave;
    private _onVisibilityChange;
    private _handleScroll;
    protected _handleSeekChange({ target }: Event): void;
    private _isLottie;
    addAnimation(configs: AnimationAttributes[], fileName?: string, shouldDownload?: boolean): Promise<{
        result?: void | ArrayBuffer;
        success: boolean;
        error?: string;
    }>;
    getLottie(): AnimationItem | null;
    play(): Promise<void>;
    pause(): void;
    stop(): void;
    destroy(): void;
    seek(value: number | string): void;
    snapshot(shouldDownload?: boolean, name?: string): string | null;
    setSubframe(value: boolean): void;
    setCount(value: number): void;
    protected _freeze(): void;
    reload(): Promise<void>;
    setSpeed(value?: number): void;
    setDirection(value: AnimationDirection): void;
    setLoop(value: boolean): void;
    togglePlay(): void | Promise<void>;
    toggleLoop(): void;
    toggleBoomerang(): void;
    private _toggleSettings;
    protected _handleSettingsClick: ({ target }: Event) => void;
    protected _handleBlur(): void;
    private _switchInstance;
    next(): void;
    prev(): void;
    convert({ animations, fileName, manifest, shouldDownload, src, typeCheck, }: {
        typeCheck?: boolean;
        manifest?: LottieManifest;
        animations?: AnimationData[];
        src?: string;
        fileName?: string;
        shouldDownload?: boolean;
    }): Promise<string | void | ArrayBuffer>;
    static get styles(): CSSStyleSheet;
}
